### PR TITLE
typo kabob -> kebab

### PR DESCRIPTION
**Pull request by Krekotun**

### CODE REVIEW

**Comment by amwmedia** [comment]
but until I actually get the code in place to support `kebab` as well as `kabob` I'm not going to pull in the PR as it would just cause confusion. 😄

**Comment by Krekotun** [comment]
@amwmedia http://wiki.c2.com/?KebabCase proof :)

**Comment by Krekotun** [comment]
more https://en.wikipedia.org/wiki/Letter_case#Special_case_styles

**Comment by amwmedia** [comment]
I don't disagree with you ;-) just don't want the documentation to be out of sync with what the code actually supports haha. Also, keeping kabobCase because it's not worth breaking backward functionality over. 

Thanks for pointing this out. It'll be in the next release for sure

**Comment by amwmedia** [comment]
@Krekotun proof! http://allrecipes.com/recipe/218486/moms-beef-shish-kabobs/

and "mom" is never wrong 😉

**Comment by Krekotun** [comment]
I forgot that it's not only in readme file :)
Of course you should keep both of them.
Sorry for messing up)

**Comment by amwmedia** [comment]
this went out in v1.7.0

**Comment by Krekotun** [comment]
Cool :)

**Pull request merged**
