### PR TITLE
Added feature: Named argument bypass

### PR DESCRIPTION
**Pull request by crutchcorn**
This feature implements #109 by adding named bypass args by using `plop generator args -- --named args` style. Additionally, if args are bypassed in the wrong way (too many args or incorrectly named args), it will throw a help page listing all arguments. 

Things from #109 that were not added:
- Typings for generator options menu. I was unsure how you wanted to implement that, so I left it out for the initial commit
- Allowing `'_'` in named args passing values. This was done so that there wouldn't have to be breaking releases in `node-plop` for the initial feature set. If requested, I can create a seperate PR for that functionality

### CODE REVIEW

**Comment by amwmedia** [comment]
yeah, don't worry too much about the breaking changes in node-plop. Each version of `plop` is set up to use a specific version of `node-plop` (version `=0.X.X`). Generally, I'll release the new `node-plop` version first, and then release a version of plop that uses it.

**Comment by amwmedia** [comment]
You can do them both in parallel if you like. I'll then checkout both branches to test it out locally and coordinate the release

**Comment by crutchcorn** [comment]
Oh golly, I totally forgot that I had not completed the work mentioned here. I'll make sure to wrap up the work here sometime this week. My bad!

**Comment by amwmedia** [comment]
I actually tried to pull this in as is for the last release but ran into some issues with errors

**Comment by crutchcorn** [comment]
Oh dear! I'll try to do my own testing, but is there any edge-cases you were able to notice unintentional behavior on?

**Comment by amwmedia** [comment]
I ran into errors when I tried to run `plop` without any arguments (if I remember correctly). The crux of the issue seems to be that one codebase was using a promise where it was expecting to be synchronous.

**Comment by crutchcorn** [comment]
Should be fixed now. I tested it and it should work. Also did a tiny bit of code cleanup

**Comment by crutchcorn** [comment]
Fixing merge conflicts currently

**Comment by crutchcorn** [comment]
@amwmedia This should be good to go. Quick tests seem to show this working and merge conflicts have been solved

**Comment by amwmedia** [comment]
Thanks, I'll try to look at this soon

**Comment by amwmedia** [comment]
Thanks! Merged! I re-organized some of the code to help with maintainability. `plop.js` was getting pretty long!

**Comment by crutchcorn** [comment]
I actually took a look at the changes of reorganization right before you commented and makes total sense 👍 Shoulda probably done so myself 😅

**Comment by amwmedia** [comment]
It's been in need of a little re-tooling for a while. This just gave me the necessary push to get it done 👍

**Pull request merged**
