### PR TITLE
Add missing import of chalk

### LINKED ISSUE #151: When invalid argument passed, does not exit gracefully
If I pass an argument on the command line that does not match a prompt name, then it exits with an error that it can't display the error message. It should display the error message it was generating, so I can see what argument I've mistyped.

```
C:\Users\colin.mackay\AppData\Roaming\npm\node_modules\plop\src\bypass.js:29
                                console.error(chalk.red('[PLOP] ') + '"' + arg + '"' + ' is an invalid argument for "' + generator.name + '"');
                                              ^

ReferenceError: chalk is not defined
    at Object.keys.forEach (C:\Users\colin.mackay\AppData\Roaming\npm\node_modules\plop\src\bypass.js:29:19)
    at Array.forEach (<anonymous>)
    at combineBypassData (C:\Users\colin.mackay\AppData\Roaming\npm\node_modules\plop\src\bypass.js:27:25)
    at runGeneratorByName (C:\Users\colin.mackay\AppData\Roaming\npm\node_modules\plop\src\plop.js:49:22)
    at Liftoff.run (C:\Users\colin.mackay\AppData\Roaming\npm\node_modules\plop\src\plop.js:72:3)
    at Liftoff.execute (C:\Users\colin.mackay\AppData\Roaming\npm\node_modules\plop\node_modules\liftoff\index.js:203:12)
    at module.exports (C:\Users\colin.mackay\AppData\Roaming\npm\node_modules\plop\node_modules\flagged-respawn\index.js:51:3)
    at Liftoff.<anonymous> (C:\Users\colin.mackay\AppData\Roaming\npm\node_modules\plop\node_modules\liftoff\index.js:195:5)
    at C:\Users\colin.mackay\AppData\Roaming\npm\node_modules\plop\node_modules\liftoff\index.js:165:9
    at C:\Users\colin.mackay\AppData\Roaming\npm\node_modules\plop\node_modules\v8flags\index.js:110:14
```

### PR DESCRIPTION
**Pull request by msheldon83**
Fixes #151 

Not much else to say about this one.

### CODE REVIEW

**Comment by amwmedia** [comment]
you are a code master 😉

**Comment by msheldon83** [comment]
Thanks for the softball :p

**Comment by phiter** [comment]
just ran across the error this is meant to fix, I guess you guys didn't release it to npm yet

**Comment by amwmedia** [comment]
not yet, looking to do that today (time allowing)

**Pull request merged**
