### PR TITLE
update custom inquirer prompts

### PR DESCRIPTION
**Pull request by adam-golab**
I added new inquirer prompts for selecting index in an array where should be added a new element.

### CODE REVIEW

**Comment by amwmedia** [comment]
Just curious, what have you used this for with plop?

**Comment by amwmedia** [comment]
Any chance you can add a gif or video showing how it works?

**Comment by adam-golab** [comment]
No problem, I'll try to create gif today. I created it to inserting new route for React-Router in chosen line.

**Comment by amwmedia** [comment]
the gif definitely helps demonstrate usage

**Pull request merged**
