### PR TITLE
Document liftoff arguments

### PR DESCRIPTION
**Pull request by nicoespeon**
I came across #37 and I found it was an easy one, so here it is:

liftoff-arguments

I didn't put these info in the README. Instead I indicated how to display plop options with `plop --help`. That way information is not duplicated, which I feel less risky to get out of sync in the future.

Also, I dropped the `verbose` argument which didn't seem to do anything. I couldn't find it in the [liftoff doc](https://github.com/js-cli/js-liftoff#launchopts-callbackenv) neither.

Does that seems good to you?

### CODE REVIEW

**Comment by amwmedia** [comment]
I see value in the `--plopfile` argument, but I'm not sure about the others. Does the `cwd` prop actually affect anything? I'm pretty sure all generators will ignore this and use the `plopfile` path by default.

**Comment by nicoespeon** [comment]
@amwmedia that's a good question.

So far these arguments [are passed to liftoff](https://github.com/amwmedia/plop/blob/master/src/plop.js#L23-L27).

I will test if they have any influence. If not, maybe we can get rid of them in the code too.

**Comment by nicoespeon** [comment]
@amwmedia after verification: they do work.

For example, from the root of the project if I run `./src/plop.js --cwd ./example/` it will resolve the plopfile.

But I think it's redundant with `--plopfile`. It adds unnecessary complexity.

As for `--completion` and `--require`, so far I don't have any use case in mind to use those.

My suggestion: get rid of these arguments to simplify the CLI. If we keep them I think it's good to have them documented.

What do you think?

**Comment by amwmedia** [comment]
After reading up more on these, I think it's fine to just leave them in place. There may be some value that I don't fully understand or make use of, but I don't think there's any harm in including these params in the help screen.

Thanks for taking this on :-)

**Comment by nicoespeon** [comment]
👍 Sounds good to me!

**Pull request merged**
