### PR TITLE
Export Typescript typings and add minor docs

### LINKED ISSUE #143: TypeScript typings
Plop is a great tool already, but do you consider adding TypeScript typings? I've noticed `node-plop` has them, but they're not being exported so I can't reuse them in my code. Also, they differ a little bit from this CLI.

In case anyone needs a temporary solution, here's a simple `.d.ts`:

```ts
import inquirer = require('inquirer');

export interface Plop {
  getGenerator(name: string): PlopGenerator;
  setGenerator(name: string, config: PlopGenerator): PlopGenerator;
}

interface PlopGenerator{
  description: string;
  prompts: inquirer.Question[];
  actions: ActionConfig[];
}

interface ActionConfig{
  type: string;
  path: string;
  templateFile: string;
  force?: boolean;
  data?: object;
  abortOnFail?: boolean;
}

interface PlopCfg{
  force: boolean;
  destBasePath: string;
}
```

### PR DESCRIPTION
**Pull request by crutchcorn**
Fixes #143

I think the TS docs are really repetative and loose, but I'm not entirely sure how I should go about adding docs support, so I wanted to get something up for feedback.

Pinging @feimosi and @tannerntannern as they were previously involved in TS with this project and I'd love to see what their thoughts are on the docs and how I could go about improving them

### CODE REVIEW

**Comment by tannerntannern** [comment]
I will need to sit down and look at this more closely, but my initial impression is that you really only need the first mention of TypeScript support and how to include it in the plopfile.  I think the typings still need a little more work (and I'll be happy to help once I can set aside some time), but when they're done right, the TS compiler should be able to infer everything just from `plop: NodePlopAPI`.

**Comment by crutchcorn** [comment]
They absolutely can just infer, but I'm the type of person who appreciated being able to manually type a lot of stuff (especially since my plop file is going to get a little out there so I'll probably need to break it out and typings help a lot there). Because of this reason I want to mention the explicit typings but I totally agree that my repeat mentions are totally unnecessary, just not sure how to go about fixing that

**Comment by tannerntannern** [comment]
In that case, perhaps group them all together under a centralized TypeScript reference section? That would make more sense to me personally, and you could #link to the relevant sections of the docs if you wanted.

**Comment by cspotcode** [comment]
Is there anything I can do to help this get merged?

In my experience, TypeScript types are usually not called out individually in the README, because the editor integration makes it really easy to discover them as you're coding.  You can `import {} from 'plop';`, put your cursor between the curly braces, and the dropdown will show you a list.  And then the tooltips let you read JSDoc descriptions, which hopefully explain the usage for each type.  That, plus sensible naming, make it straightforward to discover the API without consulting a README.

So maybe it makes sense to remove all but the first README patch.  Mention that typings exist, tell people to start with `NodePlopAPI`, and let tooltips guide people the rest of the way.

**Comment by crutchcorn** [comment]
I don't disagree they they're not usually mentioned in the README, but because of the typings not matching a some of the names in the README, and some of the typings being less than obvious I think the README mentions make sense. (I'd personally argue more docs are better than less)

As for what's been blocking: 
It's been me. 😅 

I've had a rough few months and I just need to go back and move the docs to it's own section

**Comment by cspotcode** [comment]
Does it make sense to put those docs into the .d.ts?  So they're discoverable within the editor?

**Comment by crutchcorn** [comment]
Certainly not against that - JSDoc style comments would add support for IDEs explaining things, but without having explicit mention within docs, it might be hard for a user to know that they don't have to duplicate typings. Sure there's `(typeof Plop)['method']`, but that's not obvious for newcomers to TS

**Comment by cspotcode** [comment]
@crutchcorn Anything I can do to get this merged?  You want to move the Typescript-specific docs to their own README section, right?  I can take a stab at that.

I'm trying to talk up plop at work, so getting a great IDE tooling experience is important.

**Comment by crutchcorn** [comment]
@cspotcode Actually, if you want to take over this pull request, that would be a-okay with me. The only functionality seen here is the `index.d.ts` file. When you open a new PR, let me know and I'll close this one

**Comment by crutchcorn** [comment]
Coding PR in favor of #169

**Pull request closed without merging**
